# Site settings
title:       AlenPuzic.com
email:       alen.puzic@gmail.com
author:      Alen Puzic
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://alenpuzic.com"

# Google analytics
google_analytics: UA-51689808-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: alenpuzic

# Social icons
show_social_icons: false
github_username: alenpuzic
stackoverflow_id:
twitter_username: alenpuzic
google_plus_id:
linkedin_username: alenpuzic
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
