# Site settings
title:       Alen Puzic
email:       alen.puzic@gmail.com
author:      Alen Puzic
description: "Alen Puzic's personal blog. Thoughts and ramblings on technology, cybersecurity and life."
baseurl:     ""
url:         "http://alenpuzic.com"

# Google analytics
google_analytics: UA-51689808-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: alenpuzic

# Social icons
show_social_icons: false
github_username: alenpuzic
stackoverflow_id:
twitter_username: alenpuzic
google_plus_id:
linkedin_username: alenpuzic
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
